alias apti='apt install'
alias apts='apt search'
alias aptu='apt update && sudo apt upgrade'
alias cls='clear'
alias g='git'
alias v='vim'

alias tree='tree -v'

# see: https://linuxhandbook.com/run-alias-as-sudo/
alias sudo='sudo '
