# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
  test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
  alias ls='ls --color=auto'
  #alias dir='dir --color=auto'
  #alias vdir='vdir --color=auto'

  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
fi

alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alvF'
alias tree='tree -v'

alias apti='apt install'
alias apts='apt search'
alias aptu='apt update && sudo apt upgrade'
alias cls='clear'
alias g='git'
alias v='vim'

# see: https://linuxhandbook.com/run-alias-as-sudo/
alias sudo='sudo '
