#!/usr/bin/env bash

NAME=shellcheck
INSTALL_DIR=/opt/"$NAME"
LINK_DIR=/usr/local/bin
LINK="$LINK_DIR"/"$NAME"

[ -L "$LINK" ] && rm "$LINK" || true
[ -d "$INSTALL_DIR" ] && rm -r "$INSTALL_DIR" || true
