#!/usr/bin/env bash

apt-get install -y \
    apt-transport-https bash-completion build-essential ca-certificates curl \
    dnsutils git gnupg htop jq man-db manpages nano ncdu ntfs-3g python2.7 \
    python3 python3-dev python3-pip python3-setuptools rsync \
    software-properties-common tcpdump time traceroute tree vim wget xclip \
    && pip3 install thefuck
