#!/usr/bin/env bash

apt-get install -y \
    apt-transport-https bash-completion build-essential ca-certificates curl \
    dnsutils git gnupg htop man-db manpages nano ncdu python2.7 python3 \
    python3-dev python3-pip python3-setuptools rsync \
    software-properties-common tree vim wget xclip \
    && pip3 install thefuck
